openapi: 3.0.1
info:
  contact:
    email: lampralexandros@gmail.com
  description: This is a sample openApi document
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: https://wabli.netlify.app/
  title: TempApi
  version: 1.0.0
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
- description: miniature-parakeet
  url: http://83.212.100.226:3002/v1
security:
- {}
tags:
- description: not yet ready
  name: project
- description: not yet ready
  name: workpackage
paths:
  /project:
    post:
      operationId: createproject
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/project'
        description: data to be created
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/project'
          description: successful operation
      summary: Creates the data
      tags:
      - project
      x-eov-operation-handler: controllers/ProjectController
  /project/{projectId}:
    delete:
      operationId: deleteproject
      parameters:
      - description: the Id parameter
        explode: false
        in: path
        name: projectId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: successful operation
      summary: Delete the element
      tags:
      - project
      x-eov-operation-handler: controllers/ProjectController
    get:
      operationId: getproject
      parameters:
      - description: the Id parameter
        explode: false
        in: path
        name: projectId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/project'
          description: successful operation
      summary: Get the element
      tags:
      - project
      x-eov-operation-handler: controllers/ProjectController
    put:
      operationId: updateproject
      parameters:
      - description: the Id parameter
        explode: false
        in: path
        name: projectId
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/project'
        description: data to be updated
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/project'
          description: successful operation
      summary: Updates the element
      tags:
      - project
      x-eov-operation-handler: controllers/ProjectController
  /project/getAll:
    get:
      operationId: getAllproject
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/project'
                type: array
          description: successful operation
      summary: Get all the data
      tags:
      - project
      x-method-getAll: "true"
      x-eov-operation-handler: controllers/ProjectController
  /workpackage:
    post:
      operationId: createworkpackage
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/workpackage'
        description: data to be created
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/workpackage'
          description: successful operation
      summary: Creates the data
      tags:
      - workpackage
      x-eov-operation-handler: controllers/WorkpackageController
  /workpackage/{workpackageId}:
    delete:
      operationId: deleteworkpackage
      parameters:
      - description: the Id parameter
        explode: false
        in: path
        name: workpackageId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: successful operation
      summary: Delete the element
      tags:
      - workpackage
      x-eov-operation-handler: controllers/WorkpackageController
    get:
      operationId: getworkpackage
      parameters:
      - description: the Id parameter
        explode: false
        in: path
        name: workpackageId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/workpackage'
          description: successful operation
      summary: Get the element
      tags:
      - workpackage
      x-eov-operation-handler: controllers/WorkpackageController
    put:
      operationId: updateworkpackage
      parameters:
      - description: the Id parameter
        explode: false
        in: path
        name: workpackageId
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/workpackage'
        description: data to be updated
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/workpackage'
          description: successful operation
      summary: Updates the element
      tags:
      - workpackage
      x-eov-operation-handler: controllers/WorkpackageController
  /workpackage/getAll:
    get:
      operationId: getAllworkpackage
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/workpackage'
                type: array
          description: successful operation
      summary: Get all the data
      tags:
      - workpackage
      x-method-getAll: "true"
      x-eov-operation-handler: controllers/WorkpackageController
components:
  schemas:
    project:
      example:
        projectImage:
          data: data
          name: name
        _id: _id
        projectWp: ""
        projectTitle: projectTitle
      properties:
        _id:
          type: string
        projectTitle:
          type: string
        projectWp:
          oneOf:
          - $ref: '#/components/schemas/workpackage'
          - type: string
          x-one-of-name: workpackage
        projectImage:
          $ref: '#/components/schemas/project_projectImage'
      required:
      - projectImage
      - projectTitle
      - projectWp
      type: object
    workpackage:
      example:
        _id: _id
        wpName: wpName
        wpDescription: wpDescription
      properties:
        _id:
          type: string
        wpName:
          type: string
        wpDescription:
          type: string
      required:
      - wpDescription
      - wpName
      type: object
    project_projectImage:
      example:
        data: data
        name: name
      properties:
        data:
          type: string
        name:
          type: string
      type: object
      x-isSchemaOnly: "true"
